name: Reusable Bilibili Boost

on:
  workflow_call:
    inputs:
      cli_flags:
        description: "Custom CLI flags to pass to booster.py (e.g., '--mid 123456 --increment 100 --validators 80')"
        required: true
        type: string
    secrets:
      cookies:
        description: "Bilibili cookies in Netscape format"
        required: true

jobs:
  boost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout booster repo
        uses: actions/checkout@v5
        with:
          repository: phanen/bilibili-viewcount-booster
          ref: main

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      # header matter? https://github.com/yt-dlp/yt-dlp/issues/12467#issuecomment-2677591696
      - name: Create cookies file
        run: printf %s "${{ secrets.cookies }}" > cookies.txt

      - name: Run booster
        # https://github.com/orgs/community/discussions/50481
        timeout-minutes: 20
        run: |
          uv run python scripts/booster.py \
            --cookies cookies.txt \
            ${{ inputs.cli_flags }}

      - name: Cleanup
        if: always()
        run: rm -f cookies.txt
